#!/bin/bash

# This script provides a guided way to test basic functionalities of the
# Pathos Assistant by instructing the user to run main.py with specific
# configurations and observe the output.

echo "================================================"
echo " Pathos Assistant Basic Functionality Tests"
echo "================================================"
echo ""
echo "This script will guide you through testing various components."
echo "It primarily relies on you running 'python eidos_assistant/main.py'"
echo "and using commands like '/validate_setup' and specific test queries."
echo "Please ensure your .env file in the 'eidos_assistant' directory is"
echo "configured correctly for the components you want to test."
echo ""
echo "------------------------------------------------"
echo " STEP 1: Initial Validation with /validate_setup"
echo "------------------------------------------------"
echo "1. Open your .env file and configure it for the components you wish to test"
echo "   (OpenAI LLM, Local LLM, Kokoro TTS, Local pyttsx3 TTS, Home Assistant)."
echo "2. Run the assistant: python eidos_assistant/main.py"
echo "3. In the assistant prompt, type: /validate_setup"
echo "4. Review the output carefully. It will check for common dependencies"
echo "   (ffmpeg, microphone, TTS/LLM server connectivity or local setup) and"
echo "   PicoVoice configuration."
echo "5. Address any FAIL messages by following the guidance in README.md and setup.sh."
echo ""
echo "Press Enter to continue to LLM test guidance (after you've done /validate_setup)..."
read -r

echo "------------------------------------------------"
echo " STEP 2: LLM Engine Tests"
echo "------------------------------------------------"
echo "--- Testing OpenAI Compatible LLM Engine ---"
echo "1. In your .env file, set: LLM_ENGINE_TYPE=\"openai\""
echo "2. Ensure LLM_API_BASE_URL is pointing to your OpenAI compatible server (e.g., Ollama)."
echo "3. Run: python eidos_assistant/main.py"
echo "4. At the prompt, type: Hello, who are you?"
echo "5. Observe for a valid response from the LLM. If you see connection errors,"
echo "   ensure your LLM server is running and accessible."
echo ""
echo "--- Testing Local Llama.cpp LLM Engine (if configured) ---"
echo "1. In your .env file, set: LLM_ENGINE_TYPE=\"local_llama_cpp\""
echo "2. Ensure LOCAL_LLM_MODEL_PATH points to a valid GGUF model file."
echo "   (And other LOCAL_LLM_* settings like N_GPU_LAYERS are as desired)."
echo "3. Run: python eidos_assistant/main.py"
echo "   (Note: Model loading might take some time.)"
echo "4. At the prompt, type: What is the capital of France?"
echo "5. Observe for a valid response. If you see errors, check the model path,"
echo "   permissions, and llama-cpp-python installation (see README)."
echo ""
echo "Press Enter to continue to TTS test guidance..."
read -r

echo "------------------------------------------------"
echo " STEP 3: Text-to-Speech (TTS) Tests"
echo "------------------------------------------------"
echo "--- Testing Kokoro TTS Engine (if server running) ---"
echo "1. In your .env file, set: TTS_ENGINE=\"kokoro\""
echo "2. Ensure KOKORO_TTS_BASE_URL points to your running Kokoro-FastAPI server."
echo "3. Run: python eidos_assistant/main.py"
echo "4. At the prompt, type: /say Hello from Kokoro TTS"
echo "5. Listen for audio output. Check for 'eidos_tts_output.mp3' in the 'eidos_assistant' directory."
echo "   If no sound or errors, check Kokoro server status and console logs."
echo ""
echo "--- Testing Local pyttsx3 TTS Engine ---"
echo "1. In your .env file, set: TTS_ENGINE=\"local_pyttsx3\""
echo "2. Run: python eidos_assistant/main.py"
echo "3. At the prompt, type: /say Hello from pyttsx3 local TTS"
echo "4. Listen for audio output. Check for 'eidos_tts_output.mp3'."
echo "   If no sound (especially on Linux), ensure 'espeak' is installed (see README/setup.sh)."
echo "   Playback issues on Linux might also relate to GStreamer for 'playsound'."
echo ""
echo "Press Enter to continue to STT test guidance..."
read -r

echo "------------------------------------------------"
echo " STEP 4: Speech-to-Text (STT) Test Guidance"
echo "------------------------------------------------"
echo "STT (via /listen or /always_listen) has several dependencies:"
echo " - Python libraries: openai-whisper, torch, pyaudio (for /always_listen)"
echo " - System libraries: ffmpeg, PortAudio (for /always_listen), functional microphone."
echo "The '/validate_setup' command checks for many of these."
echo ""
echo "--- Testing /listen command ---"
echo "1. Prepare a short audio file (e.g., a few seconds of speech, in .wav or .mp3 format)."
echo "   Name it something like 'my_test_audio.wav'."
echo "2. Place it in the 'eidos_assistant' directory or note its full path."
echo "3. Run: python eidos_assistant/main.py"
echo "4. At the prompt, type: /listen path/to/your/my_test_audio.wav"
echo "   (Replace with the actual path if not in the root project directory)."
echo "5. Observe for the transcribed text. If errors occur, check ffmpeg installation"
echo "   and ensure the Whisper model (base.en by default) can be downloaded/loaded."
echo ""
echo "Note: /always_listen mode is more complex and requires a working microphone,"
echo "wake word engine setup (PicoVoice), and all STT components."
echo "Refer to the README for full /always_listen setup."
echo ""
echo "Press Enter to continue to Home Assistant test guidance..."
read -r

echo "------------------------------------------------"
echo " STEP 5: Home Assistant Integration Test Guidance"
echo "------------------------------------------------"
echo "1. Ensure your Home Assistant server is running."
echo "2. In your .env file, set valid HOME_ASSISTANT_URL and HOME_ASSISTANT_TOKEN."
echo "3. Run: python eidos_assistant/main.py"
echo "4. At the prompt, use a command like:"
echo "   /ha_status light.your_actual_light_entity_id"
echo "   (Replace 'light.your_actual_light_entity_id' with a real entity ID from your HA setup)."
echo "5. Observe for the current state of the entity."
echo "6. You can also try: /ha_toggle switch.your_actual_switch_entity_id"
echo "   (Use with caution on critical devices)."
echo "If you get errors, check the URL, token, entity ID, and network connectivity to HA."
echo ""
echo "================================================"
echo " Testing guidance complete."
echo " Review the console output from 'python eidos_assistant/main.py'"
echo " for specific success or error messages from Pathos Assistant."
echo "================================================"
